#wallpaper = , ~/.config/backgrounds/temple-gruvbox.png

preload = ~/.config/backgrounds/gruvbox-workstation.png
wallpaper {
    monitor = 
    path = ~/.config/backgrounds/gruvbox-workstation.png
    fit_mode = cover
}
