unbind r
bind r source-file ~/.tmux.conf
unbind i
bind i run '~/.tmux/plugins/tpm/scripts/install_plugins.sh'

# Unbind the default prefix (Ctrl+b)
unbind C-b

# Set Alt+j as the new prefix
set -g prefix M-j
bind M-j send-prefix


set -g mouse on

bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

set-option -g status-position top
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# The gruvbos theme
set -g @plugin 'z3z1ma/tmux-gruvbox'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
